### ISSUE TITLE
Support all unicode in search box

### ISSUE THREAD

**Issue by ThomasHabets** [ThomasHabets/cmdg#67]
Currently e.g. Swedish characters don't work

**Comment by sitya** [comment]
I like cmdg very much, but solving this issue would be really great, since I have a lots of labels/folders with accent in their names (Hungarian characters), and they are inaccessible from the search box.

[thread view would be the other nice feature, but that one is not blocking the usability like this one]

thanks in advance! :)

**Comment by ThomasHabets** [comment]
I had thread view for a while, but removed it because I don't think anyone was using it.
You saying you'd use it is a data point though. I'll probably not implement it in the near term, but would accept well-written pull requests. :-)

I'll try to get to this search issue thing, though.

**Comment by ThomasHabets** [comment]
Reclassifying as bug because really all characters should work for input.

**Comment by sitya** [comment]
Works fine, thanks :)

**Comment by ThomasHabets** [comment]
Great! I just fixed the backspace key to not require extra backspaces to work as expected.

Thanks for prodding me to fix it!
