### ISSUE TITLE
BUG: Errors with special chars in German: ö ä ü

### ISSUE THREAD

**Issue by cutzenfriend** [ThomasHabets/cmdg#70]
Sending Mails with "Umlaute" in German has some UTF8 issues. 

While using NANO as editor and creating the message everything looks normal. After sending the words in the message looks like this:

 **fÃ¼r** instead of **für**

Any idea?

**Comment by ThomasHabets** [comment]
Curious. I'm from Sweden so I've put quite some effort into getting this right, both incoming and outgoing emails.

Are you saying your outgoing messages are getting this, incoming, or both?
Does it affect the subject line, the body, or both?

(so that's four combinations in total)

I just sent an email from cmdg with some "åäöü" in both subject and body, with `VISUAL` set to `nano`, and it seems to work just fine. I even tried setting `LC_ALL=de_DE.utf8` and it still worked.

My testing is mostly on Debian, with gnome-terminal.

Could you be more specific about which OS, terminal, and language settings, as well as exactly where the characters get garbled?

**Comment by ThomasHabets** [comment]
And you're running cmdg from HEAD?

**Comment by cutzenfriend** [comment]
Hi, thanks for the fast reply!

I'm using cmdg on a Macbook :) Terminal is iTerm2.

The issues was just for outgoing mails, subject line & body. But I fixed it by using "micro" as the editor instead of "nano". I think it's a nano issue on mac. 

I'm currently using version 1.0

**Comment by ThomasHabets** [comment]
Yeah I think it must be an issue with nano, then.

I'll try to do a new release soon, with 1.01. Something relevant to you that was fixed since 1.0 is better support for extended characters in email addresses. 1.0 has a bug where "reply-all" sometimes won't work in this case.

**Comment by ThomasHabets** [comment]
You could send me an email at thomas@habets.se using nano, but I expect that all I can do is look at that and say "yup, that's encoded wrong".
