### ISSUE TITLE
How to select recipient from address list?

### ISSUE THREAD

**Issue by Timbological** [ThomasHabets/cmdg#83]
Hello,

Please forgive my ignorance, when composing an email a list of addresses appears below the textbox that match what has been typed.

Is it possible to select the top option by pressing enter, as it is when adding labels, or do you have to type out the whole address?

Thanks

**Comment by ThomasHabets** [comment]
Press Control+N to move down to the first matching option.

The difference here between labels and recipients is intentional. I'm happy to hear other suggestions, but my reasoning is that I send many emails to people not in my contacts, but I basically never want to create a new label from the "add label" dialog.

I would not want autocompletion to make it hard for me to not use a contact.
